default: &default
  adapter: mysql2
  encoding: utf8
  username: root
  password:
  host: 127.0.0.1
  port: 3306

development:
  <<: *default
  database: brute_gender_development

test:
  <<: *default
  database: brute_gender_test

production:
  <<: *default
  
  username: <%= ENV['MYSQL_USERNAME'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>

  database: brute_gender_production
