# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a29dd3d335d35e01485069c6ccb8dc2fe45d71986f5d79505c74592b2e97c163c162d0e861a7de1f3f847ec019383a8e12deaa1fa140e1dd37fc1e500e9cb2a8

test:
  secret_key_base: be487a555ed315e68c21ec29d7e1ba90af9b21d4e72dcc5e70e0d2903b874932574fe2c874d0d23854bb678b74be739ae1fccc36de1ff9bab5e39b2f17d70471

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
