# encoding: UTF-8
# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema.define(version: 20170414202533) do

  # These are extensions that must be enabled in order to support this database
  enable_extension "plpgsql"
  enable_extension "cube"
  enable_extension "earthdistance"

  create_table "basebien", force: :cascade do |t|
    t.integer  "scrape_id"
    t.datetime "last_scrape_time"
    t.jsonb    "scrape_list"
    t.datetime "date"
    t.integer  "number"
    t.string   "street"
    t.string   "zip_code"
    t.string   "city"
    t.boolean  "occupied"
    t.string   "period"
    t.integer  "rooms"
    t.integer  "floor"
    t.decimal  "area"
    t.decimal  "price_area"
    t.decimal  "price"
    t.string   "map_number"
    t.string   "ref_cadastre"
    t.string   "size"
    t.string   "function"
    t.string   "old"
    t.decimal  "rent"
    t.integer  "bathroom"
    t.integer  "service_room"
    t.integer  "garage"
    t.integer  "cave"
    t.boolean  "garden"
    t.boolean  "elevator"
    t.boolean  "terrace"
    t.boolean  "tennis"
    t.boolean  "pool"
    t.boolean  "collective_heater"
    t.string   "buyer"
    t.string   "seller"
    t.decimal  "previous_amount"
    t.string   "previous_time"
    t.decimal  "latitude"
    t.decimal  "longitude"
    t.decimal  "neighbourhood_price_mean_100"
    t.decimal  "neighbourhood_price_median_100"
    t.decimal  "neighbourhood_count_100"
    t.decimal  "neighbourhood_price_mean_500"
    t.decimal  "neighbourhood_price_median_500"
    t.decimal  "neighbourhood_count_500"
    t.decimal  "neighbourhood_price_mean_1000"
    t.decimal  "neighbourhood_price_median_1000"
    t.decimal  "neighbourhood_count_1000"
    t.decimal  "neighbourhood_price_mean_2000"
    t.decimal  "neighbourhood_price_median_2000"
    t.decimal  "neighbourhood_count_2000"
  end

# Could not dump table "basebien2" because of following StandardError
#   Unknown type 'earth' for column 'lat_lng_coord'

  create_table "basebien3", force: :cascade do |t|
    t.integer  "scrape_id"
    t.datetime "last_scrape_time"
    t.jsonb    "scrape_list"
    t.datetime "date"
    t.integer  "number"
    t.string   "street"
    t.string   "zip_code"
    t.string   "city"
    t.boolean  "occupied"
    t.string   "period"
    t.integer  "rooms"
    t.integer  "floor"
    t.decimal  "area"
    t.decimal  "price_area"
    t.decimal  "price"
    t.string   "map_number"
    t.string   "ref_cadastre"
    t.string   "size"
    t.string   "function"
    t.string   "old"
    t.decimal  "rent"
    t.integer  "bathroom"
    t.integer  "service_room"
    t.integer  "garage"
    t.integer  "cave"
    t.boolean  "garden"
    t.boolean  "elevator"
    t.boolean  "terrace"
    t.boolean  "tennis"
    t.boolean  "pool"
    t.boolean  "collective_heater"
    t.string   "buyer"
    t.string   "seller"
    t.decimal  "previous_amount"
    t.string   "previous_time"
    t.decimal  "latitude"
    t.decimal  "longitude"
    t.decimal  "neighbourhood_price_mean_100"
    t.decimal  "neighbourhood_price_median_100"
    t.decimal  "neighbourhood_count_100"
    t.decimal  "neighbourhood_price_mean_500"
    t.decimal  "neighbourhood_price_median_500"
    t.decimal  "neighbourhood_count_500"
    t.decimal  "neighbourhood_price_mean_1000"
    t.decimal  "neighbourhood_price_median_1000"
    t.decimal  "neighbourhood_count_1000"
    t.decimal  "neighbourhood_price_mean_2000"
    t.decimal  "neighbourhood_price_median_2000"
    t.decimal  "neighbourhood_count_2000"
  end

  create_table "basebien_meta", force: :cascade do |t|
    t.datetime "start_time"
    t.datetime "finish_time"
    t.boolean  "success"
    t.string   "message"
    t.string   "warning_log",     array: true
    t.string   "task_id"
    t.string   "worker_hostname"
    t.integer  "ad_count"
    t.integer  "city_id"
  end

  create_table "castorus_test_17", force: :cascade do |t|
    t.integer  "scrape_id"
    t.datetime "last_scrape_time"
    t.jsonb    "scrape_list"
    t.string   "castorus_url"
    t.string   "city"
    t.integer  "city_id"
    t.decimal  "evolution"
    t.integer  "price"
    t.integer  "price_per_m2"
    t.integer  "rooms"
    t.integer  "surface"
    t.datetime "created_date"
    t.string   "description"
    t.string   "source_url"
    t.string   "characteristics",      array: true
    t.jsonb    "historic_prices"
    t.datetime "first_seen_date"
    t.jsonb    "prev_castorus_url"
    t.jsonb    "prev_city"
    t.jsonb    "prev_city_id"
    t.jsonb    "prev_evolution"
    t.jsonb    "prev_price"
    t.jsonb    "prev_price_per_m2"
    t.jsonb    "prev_rooms"
    t.jsonb    "prev_surface"
    t.jsonb    "prev_created_date"
    t.jsonb    "prev_description"
    t.jsonb    "prev_source_url"
    t.jsonb    "prev_characteristics"
    t.jsonb    "prev_first_seen_date"
  end

  create_table "castorus_test_17_meta", force: :cascade do |t|
    t.datetime "start_time"
    t.datetime "finish_time"
    t.boolean  "success"
    t.string   "message"
    t.string   "warning_log",     array: true
    t.string   "task_id"
    t.string   "worker_hostname"
    t.integer  "ad_count"
    t.integer  "city_id"
  end

  create_table "categories", force: :cascade do |t|
    t.string   "name"
    t.string   "description"
    t.string   "word_sources"
    t.integer  "word_frequency_maximum"
    t.integer  "word_score_maximum"
    t.datetime "created_at",             null: false
    t.datetime "updated_at",             null: false
  end

  create_table "category_words", force: :cascade do |t|
    t.string   "name"
    t.string   "description"
    t.boolean  "include_word"
    t.integer  "url_frequency"
    t.integer  "category_ranking"
    t.integer  "word_id"
    t.integer  "category_id"
    t.datetime "created_at",       null: false
    t.datetime "updated_at",       null: false
  end

  add_index "category_words", ["category_id"], name: "index_category_words_on_category_id", using: :btree
  add_index "category_words", ["word_id"], name: "index_category_words_on_word_id", using: :btree

  create_table "level_instances", force: :cascade do |t|
    t.integer  "level_id"
    t.integer  "user_id"
    t.integer  "complete_count"
    t.float    "correct_completion_percent"
    t.datetime "created_at",                 null: false
    t.datetime "updated_at",                 null: false
  end

  add_index "level_instances", ["level_id"], name: "index_level_instances_on_level_id", using: :btree
  add_index "level_instances", ["user_id"], name: "index_level_instances_on_user_id", using: :btree

  create_table "level_words", force: :cascade do |t|
    t.integer  "level_id"
    t.integer  "word_id"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  add_index "level_words", ["level_id"], name: "index_level_words_on_level_id", using: :btree
  add_index "level_words", ["word_id"], name: "index_level_words_on_word_id", using: :btree

  create_table "levels", force: :cascade do |t|
    t.string   "name"
    t.string   "description"
    t.string   "statistics"
    t.integer  "category_id"
    t.datetime "created_at",  null: false
    t.datetime "updated_at",  null: false
  end

  add_index "levels", ["category_id"], name: "index_levels_on_category_id", using: :btree

  create_table "prices_by_year", force: :cascade do |t|
    t.string  "neighbourhood"
    t.integer "year"
    t.integer "quarter"
    t.decimal "avg_price"
  end

  create_table "seloger", force: :cascade do |t|
    t.integer  "scrape_id"
    t.datetime "last_scrape_time"
    t.jsonb    "scrape_list"
    t.string   "mongo_id"
    t.string   "source_collection"
    t.integer  "agefemme"
    t.integer  "agehomme"
    t.integer  "anneeconstruct"
    t.string   "bilanconsoenergie"
    t.string   "bilanemissionges"
    t.string   "codeinsee"
    t.integer  "consoenergie"
    t.jsonb    "contact"
    t.string   "cp"
    t.string   "descriptif"
    t.datetime "dtcreation"
    t.datetime "dtfraicheur"
    t.integer  "emissionges"
    t.string   "firstthumb"
    t.string   "idagence"
    t.string   "idannonce"
    t.string   "idpays"
    t.string   "idpublication"
    t.string   "idsoustypebien"
    t.string   "idtiers"
    t.integer  "idtypebien"
    t.integer  "idtypetransaction"
    t.decimal  "latitude"
    t.string   "libelle"
    t.string   "llprecision"
    t.string   "logobigurl"
    t.string   "logotnyurl"
    t.decimal  "longitude"
    t.decimal  "loyer"
    t.decimal  "loyerannuel"
    t.decimal  "loyerannuelm2"
    t.string   "loyerannuelm2unite"
    t.string   "loyerannuelunite"
    t.string   "loyerunite"
    t.string   "meta_data_id"
    t.integer  "nbboxes"
    t.integer  "nbchambre"
    t.integer  "nbparkings"
    t.integer  "nbphotos"
    t.integer  "nbpiece"
    t.integer  "nbsallesdebain"
    t.integer  "nbsalleseau"
    t.integer  "nbterrasses"
    t.integer  "nbtoilettes"
    t.string   "pays"
    t.string   "permalien"
    t.jsonb    "photos"
    t.decimal  "prix"
    t.decimal  "prixbouquet"
    t.string   "prixmention"
    t.decimal  "prixrente"
    t.string   "prixunite"
    t.string   "proximite"
    t.boolean  "silibre"
    t.boolean  "silotneuf"
    t.boolean  "simandatexclusif"
    t.boolean  "simandatstar"
    t.boolean  "sipiscine"
    t.boolean  "sisejour"
    t.boolean  "siterrasse"
    t.decimal  "surface"
    t.string   "surfaceunite"
    t.decimal  "surfsejour"
    t.string   "titre"
    t.string   "trancheprix"
    t.string   "typedpe"
    t.string   "ville"
    t.string   "mongo_scrape_id"
    t.jsonb    "prev_mongo_id"
    t.jsonb    "prev_source_collection"
    t.jsonb    "prev_agefemme"
    t.jsonb    "prev_agehomme"
    t.jsonb    "prev_anneeconstruct"
    t.jsonb    "prev_bilanconsoenergie"
    t.jsonb    "prev_bilanemissionges"
    t.jsonb    "prev_codeinsee"
    t.jsonb    "prev_consoenergie"
    t.jsonb    "prev_contact"
    t.jsonb    "prev_cp"
    t.jsonb    "prev_descriptif"
    t.jsonb    "prev_dtcreation"
    t.jsonb    "prev_dtfraicheur"
    t.jsonb    "prev_emissionges"
    t.jsonb    "prev_firstthumb"
    t.jsonb    "prev_idagence"
    t.jsonb    "prev_idannonce"
    t.jsonb    "prev_idpays"
    t.jsonb    "prev_idpublication"
    t.jsonb    "prev_idsoustypebien"
    t.jsonb    "prev_idtiers"
    t.jsonb    "prev_idtypebien"
    t.jsonb    "prev_idtypetransaction"
    t.jsonb    "prev_latitude"
    t.jsonb    "prev_libelle"
    t.jsonb    "prev_llprecision"
    t.jsonb    "prev_logobigurl"
    t.jsonb    "prev_logotnyurl"
    t.jsonb    "prev_longitude"
    t.jsonb    "prev_loyer"
    t.jsonb    "prev_loyerannuel"
    t.jsonb    "prev_loyerannuelm2"
    t.jsonb    "prev_loyerannuelm2unite"
    t.jsonb    "prev_loyerannuelunite"
    t.jsonb    "prev_loyerunite"
    t.jsonb    "prev_meta_data_id"
    t.jsonb    "prev_nbboxes"
    t.jsonb    "prev_nbchambre"
    t.jsonb    "prev_nbparkings"
    t.jsonb    "prev_nbphotos"
    t.jsonb    "prev_nbpiece"
    t.jsonb    "prev_nbsallesdebain"
    t.jsonb    "prev_nbsalleseau"
    t.jsonb    "prev_nbterrasses"
    t.jsonb    "prev_nbtoilettes"
    t.jsonb    "prev_pays"
    t.jsonb    "prev_permalien"
    t.jsonb    "prev_photos"
    t.jsonb    "prev_prix"
    t.jsonb    "prev_prixbouquet"
    t.jsonb    "prev_prixmention"
    t.jsonb    "prev_prixrente"
    t.jsonb    "prev_prixunite"
    t.jsonb    "prev_proximite"
    t.jsonb    "prev_silibre"
    t.jsonb    "prev_silotneuf"
    t.jsonb    "prev_simandatexclusif"
    t.jsonb    "prev_simandatstar"
    t.jsonb    "prev_sipiscine"
    t.jsonb    "prev_sisejour"
    t.jsonb    "prev_siterrasse"
    t.jsonb    "prev_surface"
    t.jsonb    "prev_surfaceunite"
    t.jsonb    "prev_surfsejour"
    t.jsonb    "prev_titre"
    t.jsonb    "prev_trancheprix"
    t.jsonb    "prev_typedpe"
    t.jsonb    "prev_ville"
    t.jsonb    "prev_mongo_scrape_id"
  end

  add_index "seloger", ["scrape_id"], name: "seloger_scrape_id_idx", using: :btree

  create_table "seloger_meta", force: :cascade do |t|
    t.datetime "start_time"
    t.datetime "finish_time"
    t.boolean  "success"
    t.string   "message"
    t.string   "warning_log",     array: true
    t.string   "task_id"
    t.string   "worker_hostname"
    t.integer  "ad_count"
    t.integer  "postal_code"
  end

  add_index "seloger_meta", ["id"], name: "seloger_meta_id_idx", using: :btree
  add_index "seloger_meta", ["id"], name: "seloger_meta_id_idx1", using: :btree

  create_table "seloger_test", force: :cascade do |t|
    t.integer  "scrape_id"
    t.datetime "last_scrape_time"
    t.jsonb    "scrape_list"
    t.string   "mongo_id"
    t.string   "source_collection"
    t.integer  "agefemme"
    t.integer  "agehomme"
    t.integer  "anneeconstruct"
    t.string   "bilanconsoenergie"
    t.string   "bilanemissionges"
    t.string   "codeinsee"
    t.integer  "consoenergie"
    t.jsonb    "contact"
    t.string   "cp"
    t.string   "descriptif"
    t.datetime "dtcreation"
    t.datetime "dtfraicheur"
    t.integer  "emissionges"
    t.string   "firstthumb"
    t.string   "idagence"
    t.string   "idannonce"
    t.string   "idpays"
    t.string   "idpublication"
    t.string   "idsoustypebien"
    t.string   "idtiers"
    t.integer  "idtypebien"
    t.integer  "idtypetransaction"
    t.decimal  "latitude"
    t.string   "libelle"
    t.string   "llprecision"
    t.string   "logobigurl"
    t.string   "logotnyurl"
    t.decimal  "longitude"
    t.decimal  "loyer"
    t.decimal  "loyerannuel"
    t.decimal  "loyerannuelm2"
    t.string   "loyerannuelm2unite"
    t.string   "loyerannuelunite"
    t.string   "loyerunite"
    t.string   "meta_data_id"
    t.integer  "nbboxes"
    t.integer  "nbchambre"
    t.integer  "nbparkings"
    t.integer  "nbphotos"
    t.integer  "nbpiece"
    t.integer  "nbsallesdebain"
    t.integer  "nbsalleseau"
    t.integer  "nbterrasses"
    t.integer  "nbtoilettes"
    t.string   "pays"
    t.string   "permalien"
    t.jsonb    "photos"
    t.decimal  "prix"
    t.decimal  "prixbouquet"
    t.string   "prixmention"
    t.decimal  "prixrente"
    t.string   "prixunite"
    t.string   "proximite"
    t.boolean  "silibre"
    t.boolean  "silotneuf"
    t.boolean  "simandatexclusif"
    t.boolean  "simandatstar"
    t.boolean  "sipiscine"
    t.boolean  "sisejour"
    t.boolean  "siterrasse"
    t.decimal  "surface"
    t.string   "surfaceunite"
    t.decimal  "surfsejour"
    t.string   "titre"
    t.string   "trancheprix"
    t.string   "typedpe"
    t.string   "ville"
    t.jsonb    "prev_mongo_id"
    t.jsonb    "prev_source_collection"
    t.jsonb    "prev_agefemme"
    t.jsonb    "prev_agehomme"
    t.jsonb    "prev_anneeconstruct"
    t.jsonb    "prev_bilanconsoenergie"
    t.jsonb    "prev_bilanemissionges"
    t.jsonb    "prev_codeinsee"
    t.jsonb    "prev_consoenergie"
    t.jsonb    "prev_contact"
    t.jsonb    "prev_cp"
    t.jsonb    "prev_descriptif"
    t.jsonb    "prev_dtcreation"
    t.jsonb    "prev_dtfraicheur"
    t.jsonb    "prev_emissionges"
    t.jsonb    "prev_firstthumb"
    t.jsonb    "prev_idagence"
    t.jsonb    "prev_idannonce"
    t.jsonb    "prev_idpays"
    t.jsonb    "prev_idpublication"
    t.jsonb    "prev_idsoustypebien"
    t.jsonb    "prev_idtiers"
    t.jsonb    "prev_idtypebien"
    t.jsonb    "prev_idtypetransaction"
    t.jsonb    "prev_latitude"
    t.jsonb    "prev_libelle"
    t.jsonb    "prev_llprecision"
    t.jsonb    "prev_logobigurl"
    t.jsonb    "prev_logotnyurl"
    t.jsonb    "prev_longitude"
    t.jsonb    "prev_loyer"
    t.jsonb    "prev_loyerannuel"
    t.jsonb    "prev_loyerannuelm2"
    t.jsonb    "prev_loyerannuelm2unite"
    t.jsonb    "prev_loyerannuelunite"
    t.jsonb    "prev_loyerunite"
    t.jsonb    "prev_meta_data_id"
    t.jsonb    "prev_nbboxes"
    t.jsonb    "prev_nbchambre"
    t.jsonb    "prev_nbparkings"
    t.jsonb    "prev_nbphotos"
    t.jsonb    "prev_nbpiece"
    t.jsonb    "prev_nbsallesdebain"
    t.jsonb    "prev_nbsalleseau"
    t.jsonb    "prev_nbterrasses"
    t.jsonb    "prev_nbtoilettes"
    t.jsonb    "prev_pays"
    t.jsonb    "prev_permalien"
    t.jsonb    "prev_photos"
    t.jsonb    "prev_prix"
    t.jsonb    "prev_prixbouquet"
    t.jsonb    "prev_prixmention"
    t.jsonb    "prev_prixrente"
    t.jsonb    "prev_prixunite"
    t.jsonb    "prev_proximite"
    t.jsonb    "prev_silibre"
    t.jsonb    "prev_silotneuf"
    t.jsonb    "prev_simandatexclusif"
    t.jsonb    "prev_simandatstar"
    t.jsonb    "prev_sipiscine"
    t.jsonb    "prev_sisejour"
    t.jsonb    "prev_siterrasse"
    t.jsonb    "prev_surface"
    t.jsonb    "prev_surfaceunite"
    t.jsonb    "prev_surfsejour"
    t.jsonb    "prev_titre"
    t.jsonb    "prev_trancheprix"
    t.jsonb    "prev_typedpe"
    t.jsonb    "prev_ville"
  end

  create_table "seloger_test_09", force: :cascade do |t|
    t.integer  "scrape_id"
    t.datetime "last_scrape_time"
    t.jsonb    "scrape_list"
    t.string   "mongo_id"
    t.string   "source_collection"
    t.integer  "agefemme"
    t.integer  "agehomme"
    t.integer  "anneeconstruct"
    t.string   "bilanconsoenergie"
    t.string   "bilanemissionges"
    t.string   "codeinsee"
    t.integer  "consoenergie"
    t.jsonb    "contact"
    t.string   "cp"
    t.string   "descriptif"
    t.datetime "dtcreation"
    t.datetime "dtfraicheur"
    t.integer  "emissionges"
    t.string   "firstthumb"
    t.string   "idagence"
    t.string   "idannonce"
    t.string   "idpays"
    t.string   "idpublication"
    t.string   "idsoustypebien"
    t.string   "idtiers"
    t.integer  "idtypebien"
    t.integer  "idtypetransaction"
    t.decimal  "latitude"
    t.string   "libelle"
    t.string   "llprecision"
    t.string   "logobigurl"
    t.string   "logotnyurl"
    t.decimal  "longitude"
    t.decimal  "loyer"
    t.decimal  "loyerannuel"
    t.decimal  "loyerannuelm2"
    t.string   "loyerannuelm2unite"
    t.string   "loyerannuelunite"
    t.string   "loyerunite"
    t.string   "meta_data_id"
    t.integer  "nbboxes"
    t.integer  "nbchambre"
    t.integer  "nbparkings"
    t.integer  "nbphotos"
    t.integer  "nbpiece"
    t.integer  "nbsallesdebain"
    t.integer  "nbsalleseau"
    t.integer  "nbterrasses"
    t.integer  "nbtoilettes"
    t.string   "pays"
    t.string   "permalien"
    t.jsonb    "photos"
    t.decimal  "prix"
    t.decimal  "prixbouquet"
    t.string   "prixmention"
    t.decimal  "prixrente"
    t.string   "prixunite"
    t.string   "proximite"
    t.boolean  "silibre"
    t.boolean  "silotneuf"
    t.boolean  "simandatexclusif"
    t.boolean  "simandatstar"
    t.boolean  "sipiscine"
    t.boolean  "sisejour"
    t.boolean  "siterrasse"
    t.decimal  "surface"
    t.string   "surfaceunite"
    t.decimal  "surfsejour"
    t.string   "titre"
    t.string   "trancheprix"
    t.string   "typedpe"
    t.string   "ville"
    t.jsonb    "prev_mongo_id"
    t.jsonb    "prev_source_collection"
    t.jsonb    "prev_agefemme"
    t.jsonb    "prev_agehomme"
    t.jsonb    "prev_anneeconstruct"
    t.jsonb    "prev_bilanconsoenergie"
    t.jsonb    "prev_bilanemissionges"
    t.jsonb    "prev_codeinsee"
    t.jsonb    "prev_consoenergie"
    t.jsonb    "prev_contact"
    t.jsonb    "prev_cp"
    t.jsonb    "prev_descriptif"
    t.jsonb    "prev_dtcreation"
    t.jsonb    "prev_dtfraicheur"
    t.jsonb    "prev_emissionges"
    t.jsonb    "prev_firstthumb"
    t.jsonb    "prev_idagence"
    t.jsonb    "prev_idannonce"
    t.jsonb    "prev_idpays"
    t.jsonb    "prev_idpublication"
    t.jsonb    "prev_idsoustypebien"
    t.jsonb    "prev_idtiers"
    t.jsonb    "prev_idtypebien"
    t.jsonb    "prev_idtypetransaction"
    t.jsonb    "prev_latitude"
    t.jsonb    "prev_libelle"
    t.jsonb    "prev_llprecision"
    t.jsonb    "prev_logobigurl"
    t.jsonb    "prev_logotnyurl"
    t.jsonb    "prev_longitude"
    t.jsonb    "prev_loyer"
    t.jsonb    "prev_loyerannuel"
    t.jsonb    "prev_loyerannuelm2"
    t.jsonb    "prev_loyerannuelm2unite"
    t.jsonb    "prev_loyerannuelunite"
    t.jsonb    "prev_loyerunite"
    t.jsonb    "prev_meta_data_id"
    t.jsonb    "prev_nbboxes"
    t.jsonb    "prev_nbchambre"
    t.jsonb    "prev_nbparkings"
    t.jsonb    "prev_nbphotos"
    t.jsonb    "prev_nbpiece"
    t.jsonb    "prev_nbsallesdebain"
    t.jsonb    "prev_nbsalleseau"
    t.jsonb    "prev_nbterrasses"
    t.jsonb    "prev_nbtoilettes"
    t.jsonb    "prev_pays"
    t.jsonb    "prev_permalien"
    t.jsonb    "prev_photos"
    t.jsonb    "prev_prix"
    t.jsonb    "prev_prixbouquet"
    t.jsonb    "prev_prixmention"
    t.jsonb    "prev_prixrente"
    t.jsonb    "prev_prixunite"
    t.jsonb    "prev_proximite"
    t.jsonb    "prev_silibre"
    t.jsonb    "prev_silotneuf"
    t.jsonb    "prev_simandatexclusif"
    t.jsonb    "prev_simandatstar"
    t.jsonb    "prev_sipiscine"
    t.jsonb    "prev_sisejour"
    t.jsonb    "prev_siterrasse"
    t.jsonb    "prev_surface"
    t.jsonb    "prev_surfaceunite"
    t.jsonb    "prev_surfsejour"
    t.jsonb    "prev_titre"
    t.jsonb    "prev_trancheprix"
    t.jsonb    "prev_typedpe"
    t.jsonb    "prev_ville"
  end

  create_table "user_configurations", force: :cascade do |t|
    t.integer  "user_id"
    t.boolean  "sound"
    t.boolean  "speak"
    t.boolean  "microphone"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  add_index "user_configurations", ["user_id"], name: "index_user_configurations_on_user_id", using: :btree

  create_table "user_words", force: :cascade do |t|
    t.string   "word_text"
    t.string   "examples",   default: [],              array: true
    t.integer  "word_id"
    t.integer  "user_id"
    t.datetime "created_at",              null: false
    t.datetime "updated_at",              null: false
  end

  add_index "user_words", ["user_id"], name: "index_user_words_on_user_id", using: :btree
  add_index "user_words", ["word_id"], name: "index_user_words_on_word_id", using: :btree

  create_table "users", force: :cascade do |t|
    t.string   "email",                  default: "", null: false
    t.string   "encrypted_password",     default: "", null: false
    t.string   "reset_password_token"
    t.datetime "reset_password_sent_at"
    t.datetime "remember_created_at"
    t.integer  "sign_in_count",          default: 0,  null: false
    t.datetime "current_sign_in_at"
    t.datetime "last_sign_in_at"
    t.string   "current_sign_in_ip"
    t.string   "last_sign_in_ip"
    t.datetime "created_at",                          null: false
    t.datetime "updated_at",                          null: false
  end

  add_index "users", ["email"], name: "index_users_on_email", unique: true, using: :btree
  add_index "users", ["reset_password_token"], name: "index_users_on_reset_password_token", unique: true, using: :btree

  create_table "word_scores", force: :cascade do |t|
    t.integer  "level_instance_id"
    t.integer  "word_id"
    t.integer  "user_id"
    t.integer  "category_id"
    t.boolean  "correct"
    t.boolean  "seen"
    t.datetime "created_at",        null: false
    t.datetime "updated_at",        null: false
  end

  add_index "word_scores", ["category_id"], name: "index_word_scores_on_category_id", using: :btree
  add_index "word_scores", ["level_instance_id"], name: "index_word_scores_on_level_instance_id", using: :btree
  add_index "word_scores", ["user_id"], name: "index_word_scores_on_user_id", using: :btree
  add_index "word_scores", ["word_id"], name: "index_word_scores_on_word_id", using: :btree

  create_table "words", force: :cascade do |t|
    t.string   "word"
    t.string   "word_plural"
    t.string   "word_type"
    t.boolean  "locution"
    t.jsonb    "definitions"
    t.jsonb    "translations"
    t.jsonb    "semantic_relations"
    t.jsonb    "morphos"
    t.text     "alternative_forms",  default: [],              array: true
    t.string   "gender"
    t.integer  "frequency"
    t.datetime "created_at",                      null: false
    t.datetime "updated_at",                      null: false
    t.string   "Afpfp"
    t.string   "Afpfs"
    t.string   "Afpmp"
    t.string   "Afpms"
    t.string   "Nc?p"
    t.string   "Nc?s"
    t.string   "Ncfp"
    t.string   "Ncfs"
    t.string   "Ncmp"
    t.string   "Ncms"
    t.string   "Npfp"
    t.string   "Npfs"
    t.string   "Npms"
    t.string   "Npmp"
    t.string   "Vmn----"
    t.string   "Vmpp---"
    t.string   "Vmps-pf"
    t.string   "Vmps-pm"
    t.string   "Vmps-sf"
    t.string   "Vmps-sm"
    t.string   "Vmcp1p-"
    t.string   "Vmcp1s-"
    t.string   "Vmcp2p-"
    t.string   "Vmcp2s-"
    t.string   "Vmcp3p-"
    t.string   "Vmcp3s-"
    t.string   "Vmif1p-"
    t.string   "Vmif1s-"
    t.string   "Vmif2p-"
    t.string   "Vmif2s-"
    t.string   "Vmif3p-"
    t.string   "Vmif3s-"
    t.string   "Vmii1p-"
    t.string   "Vmii1s-"
    t.string   "Vmii2p-"
    t.string   "Vmii2s-"
    t.string   "Vmii3p-"
    t.string   "Vmii3s-"
    t.string   "Vmip1p-"
    t.string   "Vmip1s-"
    t.string   "Vmip2p-"
    t.string   "Vmip2s-"
    t.string   "Vmip3p-"
    t.string   "Vmip3s-"
    t.string   "Vmis1p-"
    t.string   "Vmis1s-"
    t.string   "Vmis2p-"
    t.string   "Vmis2s-"
    t.string   "Vmis3p-"
    t.string   "Vmis3s-"
    t.string   "Vmmp1p-"
    t.string   "Vmmp2p-"
    t.string   "Vmmp2s-"
    t.string   "Vmsi1p-"
    t.string   "Vmsi1s-"
    t.string   "Vmsi2p-"
    t.string   "Vmsi2s-"
    t.string   "Vmsi3p-"
    t.string   "Vmsi3s-"
    t.string   "Vmsp1p-"
    t.string   "Vmsp1s-"
    t.string   "Vmsp2p-"
    t.string   "Vmsp2s-"
    t.string   "Vmsp3p-"
    t.string   "Vmsp3s-"
  end

  create_table "zoho", force: :cascade do |t|
    t.integer  "scrape_id"
    t.datetime "last_scrape_time"
    t.jsonb    "scrape_list"
    t.string   "record_type"
    t.string   "leadid"
    t.string   "accountid"
    t.string   "contactid"
    t.string   "dealid"
    t.string   "smownerid"
    t.string   "lead_owner"
    t.string   "first_name"
    t.string   "last_name"
    t.string   "email"
    t.string   "phone"
    t.string   "lead_source"
    t.string   "lead_status"
    t.string   "smcreatorid"
    t.string   "created_by"
    t.string   "created_time"
    t.datetime "modified_time"
    t.string   "city"
    t.string   "country"
    t.boolean  "email_opt_out"
    t.datetime "last_activity_time"
    t.string   "region"
    t.decimal  "longitude"
    t.string   "estimated_price"
    t.string   "geolocalisation_quality"
    t.string   "geolocalisation_confidence"
    t.string   "geolocalisation_accuracy"
    t.string   "project_type"
    t.string   "address_raw"
    t.string   "type"
    t.string   "address"
    t.decimal  "latitude"
    t.string   "surface_apartment"
    t.string   "postal_code"
    t.string   "rooms"
    t.boolean  "manually_validated"
    t.boolean  "closed"
    t.boolean  "bien_eligible"
    t.boolean  "pas_eligible"
    t.boolean  "sms_first_contact"
    t.boolean  "preparing_visit"
    t.boolean  "voice_mail_left"
    t.boolean  "conversation"
    t.boolean  "email_sent"
    t.string   "bathrooms"
    t.decimal  "cave_surface"
    t.boolean  "cave"
    t.boolean  "elevator"
    t.decimal  "balcony_surface"
    t.decimal  "garage_surface"
    t.boolean  "tennis_court"
    t.integer  "garage_count"
    t.boolean  "pool"
    t.decimal  "surface_livable"
    t.boolean  "combles"
    t.boolean  "terrace"
    t.decimal  "terrace_surface"
    t.decimal  "surface_rdc"
    t.string   "surface_terrain"
    t.string   "bedrooms"
    t.string   "sales_timeframe"
    t.string   "departement"
    t.integer  "rails_record"
    t.string   "building_condition"
    t.string   "construction_year"
    t.string   "internal_condition"
    t.string   "floors_internal"
    t.string   "floor"
    t.string   "dropbox_folder_id"
    t.boolean  "bien_non_eligible"
    t.string   "fake"
    t.string   "non_éligible"
    t.string   "abandonné"
    t.string   "salutation"
    t.string   "company"
    t.string   "suivi"
    t.datetime "due_date"
    t.datetime "date_created"
    t.string   "trello_cards"
    t.string   "members"
    t.string   "pandas_id"
    t.string   "most_recent_trello_card_name"
    t.string   "most_recent_trello_card_id"
    t.string   "dirty_fields"
    t.string   "territories"
    t.string   "modified_by"
    t.string   "modifiedby"
    t.string   "critères_spéciaux"
    t.string   "superficie_min"
    t.string   "budget_max"
    t.string   "department"
    t.string   "contact_owner"
    t.string   "pas_de_condition_suspensives"
    t.string   "type_de_bien"
    t.string   "localisation"
    t.string   "mobile"
    t.string   "goal"
    t.string   "chambres_min"
    t.string   "currency"
    t.decimal  "amount"
    t.string   "territory"
    t.decimal  "market_price"
    t.string   "deal_name"
    t.datetime "closing_date"
    t.string   "description"
    t.string   "stage"
    t.string   "transaction"
    t.string   "sales_cycle_duration"
    t.string   "overall_sales_duration"
    t.decimal  "expected_revenue"
    t.string   "min_guaranteed_price"
    t.string   "lead_conversion_time"
    t.decimal  "probability"
    t.string   "contact_name"
    t.string   "deal_owner"
    t.string   "account_owner"
    t.boolean  "garage"
    t.string   "account_type"
    t.string   "account_name"
  end

  create_table "zoho2", force: :cascade do |t|
    t.integer  "scrape_id"
    t.datetime "last_scrape_time"
    t.jsonb    "scrape_list"
    t.string   "record_type"
    t.string   "leadid"
    t.string   "accountid"
    t.string   "contactid"
    t.string   "dealid"
    t.string   "smownerid"
    t.string   "lead_owner"
    t.string   "first_name"
    t.string   "last_name"
    t.string   "email"
    t.string   "phone"
    t.string   "lead_source"
    t.string   "lead_status"
    t.string   "smcreatorid"
    t.string   "created_by"
    t.string   "created_time"
    t.datetime "modified_time"
    t.string   "city"
    t.string   "country"
    t.boolean  "email_opt_out"
    t.datetime "last_activity_time"
    t.string   "region"
    t.decimal  "longitude"
    t.string   "estimated_price"
    t.string   "geolocalisation_quality"
    t.string   "geolocalisation_confidence"
    t.string   "geolocalisation_accuracy"
    t.string   "project_type"
    t.string   "address_raw"
    t.string   "type"
    t.string   "address"
    t.decimal  "latitude"
    t.string   "surface_apartment"
    t.string   "postal_code"
    t.string   "rooms"
    t.boolean  "manually_validated"
    t.boolean  "closed"
    t.boolean  "bien_eligible"
    t.boolean  "pas_eligible"
    t.boolean  "sms_first_contact"
    t.boolean  "preparing_visit"
    t.boolean  "voice_mail_left"
    t.boolean  "conversation"
    t.boolean  "email_sent"
    t.string   "bathrooms"
    t.decimal  "cave_surface"
    t.boolean  "cave"
    t.boolean  "elevator"
    t.decimal  "balcony_surface"
    t.decimal  "garage_surface"
    t.boolean  "tennis_court"
    t.integer  "garage_count"
    t.boolean  "pool"
    t.decimal  "surface_livable"
    t.boolean  "combles"
    t.boolean  "terrace"
    t.decimal  "terrace_surface"
    t.decimal  "surface_rdc"
    t.string   "surface_terrain"
    t.string   "bedrooms"
    t.string   "sales_timeframe"
    t.string   "departement"
    t.integer  "rails_record"
    t.string   "building_condition"
    t.string   "construction_year"
    t.string   "internal_condition"
    t.string   "floors_internal"
    t.string   "floor"
    t.string   "dropbox_folder_id"
    t.boolean  "bien_non_eligible"
    t.string   "fake"
    t.string   "non_éligible"
    t.string   "abandonné"
    t.string   "salutation"
    t.string   "company"
    t.string   "suivi"
    t.datetime "due_date"
    t.datetime "date_created"
    t.string   "trello_cards"
    t.string   "members"
    t.string   "pandas_id"
    t.string   "most_recent_trello_card_name"
    t.string   "most_recent_trello_card_id"
    t.string   "dirty_fields"
    t.string   "territories"
    t.string   "modified_by"
    t.string   "modifiedby"
    t.string   "critères_spéciaux"
    t.string   "superficie_min"
    t.string   "budget_max"
    t.string   "department"
    t.string   "contact_owner"
    t.string   "pas_de_condition_suspensives"
    t.string   "type_de_bien"
    t.string   "localisation"
    t.string   "mobile"
    t.string   "goal"
    t.string   "chambres_min"
    t.string   "currency"
    t.decimal  "amount"
    t.string   "territory"
    t.decimal  "market_price"
    t.string   "deal_name"
    t.datetime "closing_date"
    t.string   "description"
    t.string   "stage"
    t.string   "transaction"
    t.string   "sales_cycle_duration"
    t.string   "overall_sales_duration"
    t.decimal  "expected_revenue"
    t.string   "min_guaranteed_price"
    t.string   "lead_conversion_time"
    t.decimal  "probability"
    t.string   "contact_name"
    t.string   "deal_owner"
    t.string   "account_owner"
    t.boolean  "garage"
    t.string   "account_type"
    t.string   "account_name"
  end

  create_table "zoho2_meta", force: :cascade do |t|
    t.datetime "start_time"
    t.datetime "finish_time"
    t.boolean  "success"
    t.string   "message"
    t.string   "warning_log",     array: true
    t.string   "task_id"
    t.string   "worker_hostname"
    t.integer  "ad_count"
  end

  create_table "zoho_meta", force: :cascade do |t|
    t.datetime "start_time"
    t.datetime "finish_time"
    t.boolean  "success"
    t.string   "message"
    t.string   "warning_log",     array: true
    t.string   "task_id"
    t.string   "worker_hostname"
    t.integer  "ad_count"
  end

  add_foreign_key "category_words", "categories"
  add_foreign_key "category_words", "words"
  add_foreign_key "level_instances", "levels"
  add_foreign_key "level_instances", "users"
  add_foreign_key "level_words", "levels"
  add_foreign_key "level_words", "words"
  add_foreign_key "levels", "categories"
  add_foreign_key "user_configurations", "users"
  add_foreign_key "user_words", "users"
  add_foreign_key "user_words", "words"
  add_foreign_key "word_scores", "categories"
  add_foreign_key "word_scores", "level_instances"
  add_foreign_key "word_scores", "users"
  add_foreign_key "word_scores", "words"
end
